import React from "react";
import { addDecorator } from "@storybook/react";
import { withTests } from "@storybook/addon-jest";
import { Provider, createStore } from "@frontity/connect";
import "@storybook/addon-console";
import { withConsole } from "@storybook/addon-console";
import { withA11y } from "@storybook/addon-a11y";
import { addParameters } from "@storybook/react";

// import { withHTML } from "@whitespace/storybook-addon-html/react";
// addDecorator(withHTML);

// https://github.com/storybookjs/storybook-addon-console
addDecorator((storyFn, context) => withConsole()(storyFn)(context));

//github.com/atlassian-labs/storybook-addon-performance
// import { withPerformance } from "storybook-addon-performance";
// addDecorator(withPerformance);

// import { withPlayroom } from "storybook-addon-playroom";
// addDecorator(withPlayroom); // before any other decorators

addDecorator(withA11y);

const tailWindViewports = {
  all: {
    name: "All",
    styles: {
      width: "639px",
      height: "100%",
    },
  },
  sm: {
    name: "Small (sm)",
    styles: {
      width: "640px",
      height: "100%",
    },
  },
  md: {
    name: "Medium (md)",
    styles: {
      width: "768px",
      height: "100%",
    },
  },
  lg: {
    name: "Large (lg)",
    styles: {
      width: "1024px",
      height: "100%",
    },
  },
  xl: {
    name: "Extra Large (xl)",
    styles: {
      width: "1280px",
      height: "100%",
    },
  },
};

addParameters({
  viewport: { viewports: tailWindViewports },
  defaultViewport: "all",
});

// https://github.com/storybookjs/storybook-addon-console
import "@storybook/addon-console";

// The following file is generated by running `npm run test:generate-output`.
// Make sure to run it before running or building storybook!
import results from "../.jest-test-results.json";

// Enable Jest integration for all stories
addDecorator(withTests({ results }));

const defaultState = {
  frontity: {
    url: "https://test.frontity.io",
    title: "Test Frontity Blog",
    description: "WordPress installation for Frontity development",
  },
  theme: {
    menu: [
      ["Home", "/"],
      ["Nature", "/category/nature/"],
      ["Travel", "/category/travel/"],
      ["Japan", "/tag/japan/"],
      ["About Us", "/about-us/"],
    ],
    featured: {
      showOnList: false,
      showOnPost: false,
    },
  },
  source: {
    api: "https://test.frontity.io/wp-json",
  },

  router: { link: "/" },
};

// Default actions taken from node_modules/@frontity/router/__tests__/index.test.ts
const defaultActions = {
  router: {
    /*eslint no-unused-vars: ["error", { "args": "none" }]*/
    set: (state) => (link, options) => {
      console.log("Link Clicked");
    },
  },
};

// We need to expose a store in order for frontity components to work:
// Mock store technique taken from frontity test suite: https://github.com/frontity/frontity/blob/83c5eadb4dffc6275fe4d93b8d379c21449a2727/packages/connect/src/__tests__/connect.tests.jsx#L11
const store = createStore({
  state: defaultState,
  actions: defaultActions,
});
addDecorator((storyFn) => <Provider value={store}>{storyFn()}</Provider>);
